name             'gocd'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures gocd'
long_description 'Installs/Configures gocd'
version          '0.1.0'
